server:
  port: 8761 # Http tomcat port
eureka:
  instance:
    hostname: localhost
  client: # not a client , do not register with yourself
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/



# eureka:
#   instance:
#    hostname: discovery-microservice
#    port: 8001

#   client:
#     serviceUrl:
#       defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
#     registerWithEureka: false
#     fetchRegistry: false
#     server:
#       waitTimeInMsWhenSyncEmpty: 0
