# Discovery Server Access
eureka:
  instance:
    hostname: cart-microservice
  client:
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://discovery-microservice:8001/eureka/

# HTTP (Tomcat) server port
server:
  port: 9002




# Datasource config
spring:
  application:
    name: cart-service
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/carts
    username: root
    password: password
    driverClassName: org.postgresql.Driver

eureka:
  instance:
    preferIpAddress: true