# Http server port
server:
  port: 8888

management:
  security:
    enabled: false

spring:
  application:
    name: config-server
  profiles:
    default: dev
  cloud:
    config:
      server:
        native:
          searchLocations: file://${LOCAL_REPO}
        git:
#          uri: file://${GIT_LOCAL_REPO}
           uri: https://github.com/HienNguyen711/webshop-microservice/config-repo
          searchPaths: config/server


eureka:
  instance:
    hostname: config-server
    lease-expiration-duration-in-seconds: 3
  client:
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
